name: Validate Helm Chart
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Helm Lint
        run: |
          helm lint nginx-chart
      - name: Render DEV manifests
        run: |
          helm template nginx-dev nginx-chart \
            -f environments/dev/values.yaml
      - name: Render PROD manifests
        run: |
          helm template nginx-prod nginx-chart \
            -f environments/prod/values.yaml