replicaCount: 3
image:
  repository: ghcr.io/vlechuga/gitops-lab
  tag: f3f93b422d4f80800f202c8cc44731083fafb9ad
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: nginx-dev.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []  