replicaCount: 3
image:
  repository: ghcr.io/vlechuga/gitops-lab
  tag: 6c64fc8c81d14fca2cc8d41ad36352a7c3a6f1e4
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: nginx-dev.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []  